### ISSUE TITLE
version 0.6.0 is buggy

### ISSUE THREAD

**Issue by IgorYastrebov** [tparnell8/gulp-nuget-restore#10]
I have a solution with both .net and .net core projects. And we have several nuget repos (nuget.org and a private one). Here is my code:

let nugetRestore = require('gulp-nuget-restore');
let { restore } = require('gulp-dotnet-cli');
...
    gulp.src("123.sln")
        .pipe(nugetRestore())
        .pipe(restore())
        .pipe(msbuild({ ... }))

previous version 0.5.0 works fine. Latest one - 0.6.0 doing something wrong, after its nugetRestore(), packages are conflicting each other and build not working.

**Comment by TerribleDev** [comment]
I forgot to update the release notes for 0.6.0. That contained an update to nuget.exe to `4.1.0`. Could this be a breaking change in nuget?

**Comment by TerribleDev** [comment]
If you make a repo in github I'd be happy to help you debug this
