### ISSUE TITLE
update to nuget.exe version 3.4

### ISSUE THREAD

**Issue by tgourley01** [tparnell8/gulp-nuget-restore#5]
Some of the latest rc2 package versions have a minimum nuget client version of 3.4

example nuspec snip - 
`<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
    <metadata minClientVersion="3.4">
    <id>System.Diagnostics.Debug</id>
    <version>4.0.11-rc2-24027</version>`

The failure seen during restore/install is -
`Resolved actions to install package 'System.Diagnostics.Debug.4.0.11-rc2-24027'
WARNING: Install failed. Rolling back...
The 'System.Diagnostics.Debug 4.0.11-rc2-24027' package requires NuGet client version '3.4.0' or above, but the current NuGet version is '3.3.0'. To upgrade NuGet, please go to http://docs.nuget.org/consume/installing-nuget`

Can the nuget.exe version be updated?

Thanks,
Tim

**Comment by TerribleDev** [comment]
Sure. Just submit a pr with a newer version. I may not be able to get to this until the 29th of August. I am currently traveling on holiday, and have little access to Internet.

**Comment by TerribleDev** [comment]
updated in 0.5.0
