### ISSUE TITLE
Update version of nuget?

### ISSUE THREAD

**Issue by Bitfiddler** [tparnell8/gulp-nuget-restore#6]
The current version of nuget used in the gulp-nuget-restore plugin is 3.4.4 which does not detect VS2017 msbuild tools.  Could a new version be released with nuget 4.1.0 inside?  It detects VS2017 and I tried dropping this version of nuget.exe into the plugin folder and it seems to work without any further changes.

**Comment by TerribleDev** [comment]
sure, 

as a side note you can use the nugetPath argument to specify the path to the nuget exe

**Comment by TerribleDev** [comment]
0.6.0
